-- CC HALLOWEEN 
-- MARC

-- CREATION DE LA TABLE TARIF
CREATE TABLE cc_tarif (
       tar_no NUMBER(5) PRIMARY KEY,
       tar_nom VARCHAR2(50)
);

-- INSERTION DE TROIS LIGNES DANS LA TABLE CC_TARIF
INSERT INTO cc_tarif VALUES (1,'Normal');
INSERT INTO cc_tarif VALUES (2,'Réduit');
INSERT INTO cc_tarif VALUES (3,'Déguisé');
COMMIT;

-- AJOUT DE LA CLÉ ÉTRANGÈRE DU TARIF DANS LA TABLE CC_PERSONNE
ALTER TABLE cc_personne ADD per_tar_no NUMBER(5) DEFAULT 1 CONSTRAINT fk_per_tar REFERENCES cc_personne(per_no);

-- MODIFICATION DE DONNEES DANS LA TABLE CC_PERSONNE
UPDATE cc_personne
SET per_tar_no = 2
WHERE per_categorie IN ('Etudiant','Jeune');
COMMIT;

-- CREATION DE LA TABLE CC_RABAIS
CREATE TABLE cc_rabais (
       rab_tar_no NUMBER(5) CONSTRAINT fk_tarif REFERENCES cc_tarif(tar_no),
       rab_typ_no NUMBER(5) CONSTRAINT fk_type REFERENCES cc_type(typ_no),
       rab_pourcentage NUMBER(2) CONSTRAINT nn_rab_pour NOT NULL CONSTRAINT ck_rab_pour CHECK (rab_pourcentage > 10 AND rab_pourcentage < 60),
       CONSTRAINT pk_rabais PRIMARY KEY (rab_tar_no,rab_typ_no)
);

-- INSERTION DE DONNEES DANS LA TABLE CC_RABAIS
INSERT INTO cc_rabais VALUES (2,3,25);
INSERT INTO cc_rabais VALUES (3,1,50);
INSERT INTO cc_rabais VALUES (3,3,50);
COMMIT;

-- AJOUT D'UNE VALEUR PAR DEFAUT SUR LE CHAMPS ACH_NOMBRE
ALTER TABLE cc_achete MODIFY ach_nombre DEFAULT 1;

-- MODIFICATION DES VALEURS NULL PAR LES VALEURS PAR DEFAUT
UPDATE cc_achete
SET ach_nombre = DEFAULT
WHERE ach_nombre IS NULL OR ach_nombre = 0;
COMMIT;

-- MODIFICATION DU CHAMPS ACH_NOMBRE
ALTER TABLE cc_achete MODIFY ach_nombre CONSTRAINT nn_ach_nbr NOT NULL CONSTRAINT ck_ach_nbr CHECK (ach_nombre > 0);

-- CORRECTIONS DES DONNEES DE LA TABLE CC_PRODUIT

-- LES TYPES GATEAU DIMINUE DE 1 CHF
UPDATE CC_PRODUIT
SET PRO_PRIX = PRO_PRIX -1
WHERE PRO_TYP_NO = 3;
COMMIT;

/*
-- SELECTION DE LA VALEUR MAX DANS LES PRODUITS CONCERNANT LES JUS DE COURGES
SELECT MAX(PRO_PRIX) AS MAXIMUM
FROM CC_PRODUIT
WHERE PRO_NOM = 'Jus de courge';

-- COMPTER LE NOMBRE DE DOUBLONS 
SELECT COUNT(*) AS NBR_DOUBLON,PRO_NOM
FROM CC_PRODUIT
GROUP BY PRO_NOM
HAVING COUNT(*) > 1;
*/

-- CHANGEMENT DU PRODUIT "COURG-BURGER" DE TYPE GATEAU -> SNACK
-- CREATION D'UN TYPE SNACK
INSERT INTO CC_TYPE VALUES (4,'Snack');
COMMIT;

-- MODIFICATION DU TYPE DE PRODUIT GATEAU -> SNACK
UPDATE CC_PRODUIT
SET PRO_TYP_NO = 4
WHERE PRO_NOM = 'Courg''burger';
COMMIT;

-- AJOUT D'UN BURGER D'ARAIGNÉE A 4.50 CHF
INSERT INTO CC_PRODUIT VALUES (19,'Burger d''arraignée',4.5,4);
COMMIT;

-- LA FAMILLE PASTEK PASSE EN TARIF DEGUISE
UPDATE CC_PERSONNE
SET PER_TAR_NO = 3
WHERE PER_NOM = 'Pastek';
COMMIT;

-- ACHATS DE LA FAMILLE POTIRON
-- INSERTION DE LA FAMILLE POTIRON
INSERT INTO CC_PERSONNE VALUES (76,'Potiron','Joe','M',null,3);
INSERT INTO CC_PERSONNE VALUES (77,'Potiron','Jim','M',null,3);
INSERT INTO CC_PERSONNE VALUES (78,'Potiron','Claire','F',null,1);
COMMIT;

-- INSERTION DES ACHATS DE CLAIRE
INSERT INTO CC_ACHETE VALUES (78,15,2);
INSERT INTO CC_ACHETE VALUES (76,7,3);
COMMIT;

-- SELECTION DES TABLES
SELECT * FROM cc_achete;
SELECT * FROM cc_personne;
SELECT * FROM cc_produit;
SELECT * FROM cc_type;
SELECT * FROM cc_tarif;
SELECT * FROM cc_rabais;


