INSERT INTO EXE_DEPT VALUES (1,'COMPTABILITÉ');
INSERT INTO EXE_DEPT VALUES (2,'RH');
INSERT INTO EXE_DEPT VALUES (3,'...');

SELECT * FROM EXE_DEPT;
DELETE FROM EXE_DEPT;

INSERT INTO EXE_EMPLOYE VALUES (1);
