--------------------------------------------------------------------------
--Script : CRE_JOURNEE_SPORTIVE.sql
--Objet  : Création de la base de donnees JOURNEE SPORTIVE
--
--Mise à jour
--Version  Visa      Date       Commentaires
---------  ----     ----------  ------------------------------------------------
-- 1.0     MB-YJ     2018        Création
--------- --------- ----------  ------------------------------------------------
--------------------------------------------------------------------------------
-- SUPPRESSION DES TABLES JOURNEE SPORTIVE 
--------------------------------------------------------------------------------
DROP TABLE JOU_PARAMETRE;
DROP TABLE JOU_CONFRONTATION;
DROP TABLE JOU_REMPLACEMENT;
DROP TABLE JOU_ARBITRE;
DROP TABLE JOU_ELEVE;
DROP TABLE JOU_EQUIPE;
DROP TABLE JOU_PROFESSEUR;
DROP TABLE JOU_INSCRIPTION;
DROP TABLE JOU_TOURNOI;
DROP TABLE JOU_ECOLE;

--les tables qui n'ont pas de clés étrangères doivent être créer en premier lieu. Ensuite les tables avec des références peuvent être créés. !!!

--------------------------------------------------------------------------------
-- CREATION DES TABLES JOURNEE SPORTIVE 
--------------------------------------------------------------------------------

CREATE TABLE JOU_ECOLE (
ECO_ID NUMERIC(5)
  CONSTRAINT PK_ECOLE PRIMARY KEY,
ECO_NOM VARCHAR(50)
  CONSTRAINT UQ_ECO_NOM UNIQUE   --RG11
  CONSTRAINT NN_ECO_NOM NOT NULL,
ECO_ADRESSE VARCHAR(50)
  CONSTRAINT NN_ECO_ADRESSE NOT NULL,
ECO_NPA NUMERIC(4)
  CONSTRAINT NN_ECO_NPA NOT NULL
  CONSTRAINT CK_ECO_NPA CHECK(ECO_NPA BETWEEN 1200 AND 1300),  --RG05
ECO_LOCALITE VARCHAR(50)
  CONSTRAINT NN_ECO_LOCALITE NOT NULL
);

CREATE TABLE JOU_TOURNOI (
TOU_ID NUMERIC(5)
  CONSTRAINT PK_TOURNOI PRIMARY KEY,
TOU_DATE DATE
  CONSTRAINT NN_TOU_DATE NOT NULL,
TOU_DESIGNATION VARCHAR(50)
  CONSTRAINT UQ_TOU_DESIGNATION UNIQUE  --RG12
  CONSTRAINT NN_TOU_DESIGNATION NOT NULL
);

CREATE TABLE JOU_INSCRIPTION (
ECO_ID NUMERIC(5)
  CONSTRAINT FK_INSCRIPTION_ECOLE REFERENCES JOU_ECOLE(ECO_ID)
  CONSTRAINT NN_ECO_ID NOT NULL,
TOU_ID NUMERIC(5)
  CONSTRAINT FK_INSCRIPTION_TOURNOI REFERENCES JOU_TOURNOI(TOU_ID)
  CONSTRAINT NN_TOU_ID NOT NULL,
INS_DATE DATE
  CONSTRAINT NN_INS_DATE NOT NULL,
  CONSTRAINT PK_INSCRIPTION PRIMARY KEY(ECO_ID,TOU_ID)
);

CREATE TABLE JOU_PROFESSEUR (
PRO_ID NUMERIC(5)
  CONSTRAINT PK_PROFESSEUR PRIMARY KEY,
PRO_TYPE NUMERIC(1)
  CONSTRAINT CK_PRO_TYPE CHECK(PRO_TYPE BETWEEN 1 AND 2),  --RG10
PRO_NOM VARCHAR(50)
  CONSTRAINT CK_PRO_NOM CHECK(PRO_NOM=UPPER(PRO_NOM)), --RG03
PRO_PRENOM VARCHAR(50),
  --CONSTRAINT CK_PRO_PRENOM CHECK(PRO_PRENOM=INITCAP(PRO_PRENOM)), --RG04
PRO_DATE_DE_NAISSANCE DATE,
PRO_EMAIL VARCHAR(50),
PRO_TELEPHONE NUMERIC(10),
PRO_ADRESSE VARCHAR(50),
PRO_NPA NUMERIC(4)
  CONSTRAINT CK_PRO_NPA CHECK(PRO_NPA BETWEEN 1200 AND 1300), --RG05
PRO_LOCALITE VARCHAR(50),
PRO_MDP VARCHAR(50)
);

CREATE TABLE JOU_EQUIPE (
EQU_ID NUMERIC(5)
  CONSTRAINT PK_EQUIPE PRIMARY KEY,
ECO_ID NUMERIC(5)
  CONSTRAINT FK_EQUIPE_ECOLE REFERENCES JOU_ECOLE(ECO_ID),
PRO_ID NUMERIC(5)
  CONSTRAINT FK_EQUIPE_PROFESSEUR REFERENCES JOU_PROFESSEUR(PRO_ID),
EQU_NOM VARCHAR(50)
  CONSTRAINT NN_EQU_NOM NOT NULL,
EQU_DEGRE VARCHAR(1)
  CONSTRAINT CK_EQU_DEGRE CHECK(EQU_DEGRE IN('A','B','C','D'))  --RG06
);

CREATE TABLE JOU_ELEVE (
ELE_ID NUMERIC(5)
  CONSTRAINT PK_ELEVE PRIMARY KEY,
EQU_ID NUMERIC(5)
  CONSTRAINT FK_ELEVE_EQUIPE REFERENCES JOU_EQUIPE(EQU_ID)
  CONSTRAINT NN_EQU_ID NOT NULL,
ELE_NOM VARCHAR(50)
  CONSTRAINT CK_ELE_NOM CHECK(ELE_NOM=UPPER(ELE_NOM)), --RG03,
ELE_PRENOM VARCHAR(50),
  --CONSTRAINT CK_ELE_PRENOM CHECK(ELE_PRENOM=INITCAP(ELE_PRENOM)), --RG04
ELE_DATE_DE_NAISSANCE DATE,
ELE_EMAIL VARCHAR(50),
ELE_TELEPHONE NUMERIC(10),
ELE_ADRESSE VARCHAR(50),
ELE_NPA NUMERIC(4)
  CONSTRAINT CK_ELE_NPA CHECK(ELE_NPA BETWEEN 1200 AND 1300),  --RG05
ELE_LOCALITE VARCHAR(50)
);

CREATE TABLE JOU_ARBITRE (
ARB_ID NUMERIC(5)
  CONSTRAINT PK_ARBITRE PRIMARY KEY,
ARB_NOM VARCHAR(50)
  CONSTRAINT CK_ARB_NOM CHECK(ARB_NOM=UPPER(ARB_NOM)), --RG03
ARB_PRENOM VARCHAR(50),
  --CONSTRAINT CK_ARB_PRENOM CHECK(ARB_PRENOM=INITCAP(ARB_PRENOM)), --RG04
ARB_DATE_DE_NAISSANCE DATE,
ARB_EMAIL VARCHAR(50),
ARB_TELEPHONE NUMERIC(10),
ARB_ADRESSE VARCHAR(50),
ARB_NPA NUMERIC(4)
  CONSTRAINT CK_ARB_NPA CHECK(ARB_NPA BETWEEN 1200 AND 1300),  --RG05
ARB_LOCALITE VARCHAR(50),
ARB_MDP VARCHAR(50)
);

CREATE TABLE JOU_REMPLACEMENT(
REM_PRO_ID NUMERIC(5)
  CONSTRAINT FK_REMPLACEMENT_PROFESSEUR REFERENCES JOU_PROFESSEUR(PRO_ID)
  CONSTRAINT NN_REM_PRO_ID NOT NULL,
REM_PRO_ID_PROFESSEUR NUMERIC(5)
  CONSTRAINT FK_REMPLACEMENT_PROFESSEUR2 REFERENCES JOU_PROFESSEUR(PRO_ID)
  CONSTRAINT NN_REM_PRO_ID_PROFESSEUR NOT NULL,
CONSTRAINT PK_REMPLACEMENT PRIMARY KEY(REM_PRO_ID,REM_PRO_ID_PROFESSEUR)
);

CREATE TABLE JOU_CONFRONTATION(
CON_ID NUMERIC(5)
  CONSTRAINT PK_CONFRONTATION PRIMARY KEY,
EQU_ID NUMERIC(5)
  CONSTRAINT FK_CONFRONTATION_EQUIPE_1 REFERENCES JOU_EQUIPE(EQU_ID),
EQU_ID_RECOIT NUMERIC(5)
  CONSTRAINT FK_CONFRONTATION_EQUIPE_2 REFERENCES JOU_EQUIPE(EQU_ID),
TOU_ID NUMERIC(5)
  CONSTRAINT FK_CONFRONTATION_TOURNOI REFERENCES JOU_TOURNOI(TOU_ID),
ARB_ID NUMERIC(5)
  CONSTRAINT FK_CONFRONTATION_ARBITRE REFERENCES JOU_ARBITRE(ARB_ID),
CON_ACTIVITES VARCHAR(50),
  CONSTRAINT CK_CON_ACTIVITES CHECK(CON_ACTIVITES IN('FOOT','BASKET','BALLE ASSISE','VOLLEY','ULTIMATE FREESBEE','TIR A LA CORDE','PUZZLE COURSE')),
CON_NBPOINTVISITEUR NUMERIC(1)
  CONSTRAINT CK_CON_NBPOINTVISITEUR CHECK(CON_NBPOINTVISITEUR IN(0,1,3))  --RG09
  CONSTRAINT NN_CON_NBPOINTVISITEUR NOT NULL,
CON_NBPOINTRECEVEUR NUMERIC(1)
  CONSTRAINT CK_CON_NBPOINTRECEVEUR CHECK(CON_NBPOINTRECEVEUR IN(0,1,3))  --RG09
  CONSTRAINT NN_CON_NBPOINTRECEVEUR NOT NULL
);

CREATE TABLE JOU_PARAMETRE(
PAR_ID NUMERIC(5)
  CONSTRAINT PK_PARAMETRE PRIMARY KEY,
PAR_EMPLACEMENT VARCHAR(50),
PAR_FRAIS_INSCRIPTION NUMERIC(3),
PAR_HEURE_RDV VARCHAR(5),
PAR_PRIX VARCHAR(50),
PAR_DUREE_CONFRONTATION NUMERIC(2)
  CONSTRAINT CK_PAR_DUREE_CONF CHECK(PAR_DUREE_CONFRONTATION = 10),  --RG07
PAR_HEURE_DEBUT_TOURNOI VARCHAR(5),
PAR_HEURE_FIN_TOURNOI VARCHAR(5),
PAR_HEURE_RDV_ORGANISATEUR VARCHAR(5),
PAR_TEMPS_PAUSE_MIDI NUMERIC(1)
  CONSTRAINT CK_PAR_TEMPS_PAUSE CHECK(PAR_TEMPS_PAUSE_MIDI BETWEEN 1 AND 2)  --RG08
);

/*
CREATE TABLE JOU_PERSONNE (
PER_ID NUMERIC(5)
  CONSTRAINT PK_PERSONNE PRIMARY KEY,
EQU_ID_PERSONNE NUMERIC(5)
  CONSTRAINT NN_EQU_ID_PERSONNE NOT NULL,
PER_NOM VARCHAR(30)
  CONSTRAINT NN_PER_NOM NOT NULL,
PER_PRENOM VARCHAR(30)
  CONSTRAINT NN_PER_PRENOM NOT NULL,
PER_DATE_DE_NAISSANCE VARCHAR(10),
PER_EMAIL VARCHAR(30),
PER_TELEPHONE NUMERIC(10),
PER_ADRESSE VARCHAR(30),
PER_NPA NUMERIC(4),
PER_LOCALITE VARCHAR(30),
PER_TYPE VARCHAR(30)
  CONSTRAINT CK_PER_TYPE CHECK(PER_TYPE IN('ELEVE','PROFESSEUR','ARBITRE')),
PER_EQU_ID NUMERIC(4)
  CONSTRAINT FK_PERSONNE_EQUIPE REFERENCES JOU_EQUIPE(EQU_ID),
PER_PRO_TYPE VARCHAR(30)
  CONSTRAINT CK_PER_PRO_TYPE CHECK(PER_PRO_TYPE IN('PRINCIPAL','SIMPLE'))
);
*/